import json
import nbformat as nbf
import os
import uuid
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)

class WhiteboxNotebookGenerator:
    """
    Generates a SageMaker-style Jupyter Notebook that reproduces
    the winning AutoML pipeline (preprocessing + model training).
    """
    
    def __init__(self, config: Dict[str, Any], best_params: Dict[str, Any], feature_names: List[str] = None):
        self.config = config
        self.best_params = best_params
        self.feature_names = feature_names or []
        self.nb = nbf.v4.new_notebook()
        
    def generate(self, output_path: str = None) -> str:
        """Constructs the notebook and saves it to disk."""
        
        # 1. Header & Intro
        self._add_markdown("# AutoMLOps Candidate Definition Notebook")
        self._add_markdown(
            "This notebook was automatically generated by AutoMLOps-Studio.\n"
            "It allows you to inspect, customize, and execute the winning machine learning pipeline independently."
        )
        
        # 2. Experiment Info
        task_type = self.config.get('task', 'Unknown Task')
        target_col = self.config.get('target', 'Unknown Target')
        model_name = self.best_params.get('model_name', 'Unknown Model')
        self._add_markdown(f"**Task Type:** {task_type.capitalize()}\n**Target Column:** {target_col}\n**Selected Model:** {model_name}")
        
        # 3. Imports
        self._add_markdown("### 1. Setup & Imports")
        self._add_code(
            "import pandas as pd\n"
            "import numpy as np\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.metrics import accuracy_score, f1_score, mean_squared_error, r2_score\n"
        )
        
        # 4. Data Loading (Simulated for reproducibility)
        self._add_markdown("### 2. Data Loading")
        self._add_markdown("Load your original dataset here. The code below assumes you have loaded it into a pandas DataFrame named `df`.")
        self._add_code(
            "# Replace with your actual dataset path\n"
            "# df = pd.read_csv('your_dataset.csv')\n\n"
            f"target_col = '{target_col}'\n"
            "# X = df.drop(columns=[target_col])\n"
            "# y = df[target_col]\n"
            "# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)"
        )
        
        # 5. Model Definition
        self._add_markdown("### 3. Model Definition")
        self._add_markdown(
            f"Instantiating the winning **{model_name}** model with the optimal hyperparameters found during the AutoML search."
        )
        
        model_code = self._get_model_instantiation_code()
        self._add_code(model_code)
        
        # 6. Training & Evaluation
        self._add_markdown("### 4. Training and Evaluation")
        self._add_code(
            "# Train the model\n"
            "# model.fit(X_train, y_train)\n\n"
            "# Predict and Evaluate\n"
            "# preds = model.predict(X_test)\n"
            f"# if '{task_type}' == 'classification':\n"
            "#     print('Accuracy:', accuracy_score(y_test, preds))\n"
            "# else:\n"
            "#     print('MSE:', mean_squared_error(y_test, preds))"
        )
        
        # Save to disk
        if not output_path:
            filename = f"automl_candidate_pipeline_{uuid.uuid4().hex[:6]}.ipynb"
            output_path = os.path.join(os.getcwd(), filename)
            
        with open(output_path, 'w', encoding='utf-8') as f:
            nbf.write(self.nb, f)
            
        logger.info(f"Whitebox Notebook generated at: {output_path}")
        return output_path

    def _add_markdown(self, text: str):
        self.nb.cells.append(nbf.v4.new_markdown_cell(text))
        
    def _add_code(self, code: str):
        self.nb.cells.append(nbf.v4.new_code_cell(code))
        
    def _get_model_instantiation_code(self) -> str:
        """Converts best_params into a python code string that instantiates the model."""
        model_name = self.best_params.get('model_name', '')
        params = {k: v for k, v in self.best_params.items() if k != 'model_name'}
        
        # Format params dict into kwargs string
        kwargs_str = ", ".join([f"{k}={repr(v)}" for k, v in params.items()])
        
        if "XGB" in model_name:
            import_str = "from xgboost import XGBClassifier, XGBRegressor"
            model_class = "XGBClassifier" if self.config.get('task') == 'classification' else "XGBRegressor"
        elif "LGBM" in model_name:
            import_str = "from lightgbm import LGBMClassifier, LGBMRegressor"
            model_class = "LGBMClassifier" if self.config.get('task') == 'classification' else "LGBMRegressor"
        elif "CatBoost" in model_name:
            import_str = "from catboost import CatBoostClassifier, CatBoostRegressor"
            model_class = "CatBoostClassifier" if self.config.get('task') == 'classification' else "CatBoostRegressor"
        elif "RandomForest" in model_name:
            import_str = "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor"
            model_class = "RandomForestClassifier" if self.config.get('task') == 'classification' else "RandomForestRegressor"
        elif "LogisticRegression" in model_name or "Ridge" in model_name or "Lasso" in model_name:
            import_str = "from sklearn.linear_model import LogisticRegression, Ridge, Lasso"
            model_class = model_name
        else:
            import_str = "# Import your custom model here"
            model_class = model_name or "YourModelClass"

        code = f"{import_str}\n\nmodel = {model_class}({kwargs_str})\nprint(model)"
        return code
