import json
import nbformat as nbf
import os
import uuid
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)

class WhiteboxNotebookGenerator:
    """
    Generates a SageMaker-style Jupyter Notebook that reproduces
    the winning AutoML pipeline (preprocessing + model training).
    """
    
    def __init__(self, config: Dict[str, Any], best_params: Dict[str, Any], feature_names: List[str] = None):
        self.config = config
        self.best_params = best_params
        self.feature_names = feature_names or []
        self.nb = nbf.v4.new_notebook()
        
    def generate(self, output_path: str = None) -> str:
        """Constructs the notebook and saves it to disk."""
        
        # 1. Header & Intro
        self._add_markdown("# AutoMLOps Candidate Definition Notebook")
        self._add_markdown(
            "This notebook was automatically generated by Multi-AutoML-Interface.\n"
            "It allows you to inspect, customize, and execute the winning machine learning pipeline independently."
        )
        
        # Table of Contents
        self._add_markdown(
            "## Table of Contents\n"
            "- [1. Setup & Imports](#1.-Setup-&-Imports)\n"
            "- [2. Data Loading](#2.-Data-Loading)\n"
            "- [3. Data Preprocessing (Feature Engineering)](#2.5.-Data-Preprocessing-(Feature-Engineering))\n"
            "- [4. Model Definition](#3.-Model-Definition)\n"
            "- [5. Training and Evaluation](#4.-Training-and-Evaluation)"
        )
        
        # 2. Experiment Info
        task_type = self.config.get('task', 'Unknown Task')
        target_col = self.config.get('target', 'Unknown Target')
        model_name = self.best_params.get('model_name', 'Unknown Model')
        opt_metric = self.config.get('optimization_metric', 'accuracy')
        
        self._add_markdown(
            f"**Task Type:** {task_type.capitalize()}\n"
            f"**Target Column:** {target_col}\n"
            f"**Selected Model:** {model_name}\n"
            f"**Optimization Metric:** `{opt_metric.upper()}`"
        )
        
        self._add_markdown(f"> **Optimization Target:** This pipeline was automatically tuned by Multi-AutoML-Interface to optimize the **{opt_metric.upper()}** metric.")
        
        # 3. Imports
        self._add_markdown("### 1. Setup & Imports")
        self._add_code(
            "import pandas as pd\n"
            "import numpy as np\n"
            "import mlflow\n"
            "from sklearn.model_selection import train_test_split\n"
            "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error\n"
            "from src.processor import AutoMLDataProcessor\n"
        )
        
        # 4. Data Loading
        self._add_markdown("### 2. Data Loading")
        shuffle = "False" if task_type == 'time_series' else "True"
        
        dataset_path = self.config.get('dataset_path')
        if dataset_path:
            self._add_markdown("Loading the exact dataset used during the AutoML session.")
            safe_path = dataset_path.replace('\\', '\\\\')
            self._add_code(
                f"df = pd.read_csv('{safe_path}')\n\n"
                f"target_col = '{target_col}'\n"
                f"X = df.drop(columns=[target_col])\n"
                f"y = df[target_col]\n"
                f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle={shuffle})"
            )
        else:
            self._add_markdown("Load your original dataset here. The code below assumes you have loaded it into a pandas DataFrame named `df`.")
            self._add_code(
                "# Replace with your actual dataset path\n"
                "# df = pd.read_csv('your_dataset.csv')\n\n"
                f"target_col = '{target_col}'\n"
                "# X = df.drop(columns=[target_col])\n"
                "# y = df[target_col]\n"
                f"# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle={shuffle})"
            )
        
        # 4.5. Data Preprocessing
        self._add_markdown("### 2.5. Data Preprocessing (Feature Engineering)")
        self._add_markdown(
            "Instantiating the exact data processor used during the AutoML session.\n"
            "This step handles missing values, categorical encoding, NLP embeddings, and Deep Feature Synthesis (DFS)."
        )
        self._add_code(
            f"processor = AutoMLDataProcessor(target_column='{target_col}', task_type='{task_type}')\n\n"
            "# Fit the processor on training data and transform it\n"
            "X_train_proc, y_train_proc = processor.fit_transform(X_train, y_train)\n\n"
            "# Transform the test data using the fitted processor\n"
            "X_test_proc, y_test_proc = processor.transform(X_test, y_test)"
        )
        
        # 5. Model Definition
        self._add_markdown("### 3. Model Definition")
        self._add_markdown(
            f"Instantiating the winning **{model_name}** model with the optimal hyperparameters found during the AutoML search."
        )
        
        model_code = self._get_model_instantiation_code()
        self._add_code(model_code)
        
        # 6. Training & Evaluation
        self._add_markdown("### 4. Training and Evaluation")
        
        metric_map = {
            'accuracy': ('accuracy_score', ''),
            'f1': ('f1_score', ", average='macro'"),
            'precision': ('precision_score', ", average='macro'"),
            'recall': ('recall_score', ", average='macro'"),
            'roc_auc': ('roc_auc_score', ''),
            'r2': ('r2_score', ''),
            'rmse': ('root_mean_squared_error', ''),
            'mae': ('mean_absolute_error', ''),
            'mape': ('mean_absolute_percentage_error', '')
        }
        metric_fn, metric_kwargs = metric_map.get(opt_metric, ('accuracy_score' if task_type == 'classification' else 'mean_squared_error', ''))
        
        if dataset_path:
            self._add_code(
                "mlflow.set_experiment('Whitebox_Notebook_Runs')\n"
                "with mlflow.start_run(run_name='Manual_Execution'):\n"
                f"    mlflow.log_param('model', '{model_name}')\n"
                "    # Train the model\n"
                "    model.fit(X_train_proc, y_train_proc)\n\n"
                "    # Predict and Evaluate\n"
                "    preds = model.predict(X_test_proc)\n"
                f"    score = {metric_fn}(y_test_proc, preds{metric_kwargs})\n"
                f"    print('{opt_metric.upper()}:', score)\n"
                f"    mlflow.log_metric('{opt_metric}', score)\n\n"
                "    # Save Model\n"
                "    try:\n"
                "        mlflow.sklearn.log_model(model, 'model')\n"
                "    except Exception:\n"
                "        pass"
            )
        else:
            self._add_code(
                "# mlflow.set_experiment('Whitebox_Notebook_Runs')\n"
                "# with mlflow.start_run(run_name='Manual_Execution'):\n"
                f"#     mlflow.log_param('model', '{model_name}')\n"
                "#     # Train the model\n"
                "#     model.fit(X_train_proc, y_train_proc)\n\n"
                "#     # Predict and Evaluate\n"
                "#     preds = model.predict(X_test_proc)\n"
                f"#     score = {metric_fn}(y_test_proc, preds{metric_kwargs})\n"
                f"#     print('{opt_metric.upper()}:', score)\n"
                f"#     mlflow.log_metric('{opt_metric}', score)\n\n"
                "#     # Save Model\n"
                "#     try:\n"
                "#         mlflow.sklearn.log_model(model, 'model')\n"
                "#     except Exception:\n"
                "#         pass"
            )
        
        # Save to disk
        if not output_path:
            filename = f"automl_candidate_pipeline_{uuid.uuid4().hex[:6]}.ipynb"
            output_path = os.path.join(os.getcwd(), filename)
            
        with open(output_path, 'w', encoding='utf-8') as f:
            nbf.write(self.nb, f)
            
        logger.info(f"Whitebox Notebook generated at: {output_path}")
        return output_path

    def _add_markdown(self, text: str):
        self.nb.cells.append(nbf.v4.new_markdown_cell(text))
        
    def _add_code(self, code: str):
        self.nb.cells.append(nbf.v4.new_code_cell(code))
        
    def _get_model_instantiation_code(self) -> str:
        """Converts best_params into a python code string that instantiates the model."""
        model_name = self.best_params.get('model_name', '')
        params = {k: v for k, v in self.best_params.items() if k != 'model_name'}
        
        # Format params dict into kwargs string
        kwargs_str = ", ".join([f"{k}={repr(v)}" for k, v in params.items()])
        
        if "XGB" in model_name:
            import_str = "from xgboost import XGBClassifier, XGBRegressor"
            model_class = "XGBClassifier" if self.config.get('task') == 'classification' else "XGBRegressor"
        elif "LGBM" in model_name:
            import_str = "from lightgbm import LGBMClassifier, LGBMRegressor"
            model_class = "LGBMClassifier" if self.config.get('task') == 'classification' else "LGBMRegressor"
        elif "CatBoost" in model_name:
            import_str = "from catboost import CatBoostClassifier, CatBoostRegressor"
            model_class = "CatBoostClassifier" if self.config.get('task') == 'classification' else "CatBoostRegressor"
        elif "RandomForest" in model_name:
            import_str = "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor"
            model_class = "RandomForestClassifier" if self.config.get('task') == 'classification' else "RandomForestRegressor"
        elif "LogisticRegression" in model_name or "Ridge" in model_name or "Lasso" in model_name:
            import_str = "from sklearn.linear_model import LogisticRegression, Ridge, Lasso"
            model_class = model_name
        else:
            import_str = "# Import your custom model here"
            model_class = model_name or "YourModelClass"

        code = f"{import_str}\n\nmodel = {model_class}({kwargs_str})\nprint(model)"
        return code
