name: Build Desktop App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite rodar o workflow manualmente pela aba Actions

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Build Electron App (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build-win

      - name: Build Electron App (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build-mac

      - name: Build Electron App (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build-linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multi-automl-desktop-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
          retention-days: 7
